import "array"
data =
    array.from(
        rows: [
            {
                _time: 2025-04-21T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2025-04-21T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.62,
            },
            {
                _time: 2025-04-21T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2025-04-21T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.82,
            },
            {
                _time: 2025-04-21T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.82,
            },
            {
                _time: 2025-04-21T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2025-04-21T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.42,
            },
            {
                _time: 2025-04-21T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.72,
            },
            {
                _time: 2025-04-22T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.22,
            },
            {
                _time: 2025-04-22T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.92,
            },
            {
                _time: 2025-04-22T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.82,
            },
            {
                _time: 2025-04-22T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.22,
            },
            {
                _time: 2025-04-22T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.62,
            },
            {
                _time: 2025-04-22T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.52,
            },
            {
                _time: 2025-04-22T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.82,
            },
            {
                _time: 2025-04-22T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.22,
            },
            {
                _time: 2025-04-22T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2025-04-22T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2025-04-22T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2025-04-22T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.72,
            },
            {
                _time: 2025-04-22T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2025-04-22T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2025-04-22T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2025-04-22T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.72,
            },
            {
                _time: 2025-04-22T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2025-04-22T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2025-04-22T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2025-04-22T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.72,
            },
            {
                _time: 2025-04-22T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.62,
            },
            {
                _time: 2025-04-22T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.82,
            },
            {
                _time: 2025-04-22T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.82,
            },
            {
                _time: 2025-04-23T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.52,
            },
            {
                _time: 2025-04-23T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.22,
            },
            {
                _time: 2025-04-23T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.92,
            },
            {
                _time: 2025-04-23T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.02,
            },
            {
                _time: 2025-04-23T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.72,
            },
            {
                _time: 2025-04-23T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.62,
            },
            {
                _time: 2025-04-23T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.02,
            },
            {
                _time: 2025-04-23T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2025-04-23T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2025-04-23T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2025-04-23T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.42,
            },
            {
                _time: 2025-04-23T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2025-04-23T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.12,
            },
            {
                _time: 2025-04-23T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2025-04-23T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2025-04-23T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2025-04-23T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.62,
            },
            {
                _time: 2025-04-23T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2025-04-23T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.42,
            },
            {
                _time: 2025-04-23T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2025-04-23T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2025-04-23T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.32,
            },
            {
                _time: 2025-04-23T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.12,
            },
            {
                _time: 2025-04-24T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.62,
            },
            {
                _time: 2025-04-24T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.52,
            },
            {
                _time: 2025-04-24T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.72,
            },
            {
                _time: 2025-04-24T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.62,
            },
            {
                _time: 2025-04-24T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.82,
            },
            {
                _time: 2025-04-24T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.02,
            },
            {
                _time: 2025-04-24T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.52,
            },
            {
                _time: 2025-04-24T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2025-04-24T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.32,
            },
            {
                _time: 2025-04-24T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.82,
            },
            {
                _time: 2025-04-24T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.82,
            },
            {
                _time: 2025-04-24T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2025-04-24T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2025-04-24T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2025-04-24T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2025-04-24T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.92,
            },
            {
                _time: 2025-04-24T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2025-04-24T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.92,
            },
            {
                _time: 2025-04-24T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.42,
            },
            {
                _time: 2025-04-24T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2025-04-24T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.52,
            },
            {
                _time: 2025-04-24T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.42,
            },
            {
                _time: 2025-04-24T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.32,
            },
            {
                _time: 2025-04-25T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.92,
            },
            {
                _time: 2025-04-25T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.72,
            },
            {
                _time: 2025-04-25T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.42,
            },
            {
                _time: 2025-04-25T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.52,
            },
            {
                _time: 2025-04-25T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.92,
            },
            {
                _time: 2025-04-25T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.52,
            },
            {
                _time: 2025-04-25T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.12,
            },
            {
                _time: 2025-04-25T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.82,
            },
            {
                _time: 2025-04-25T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2025-04-25T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.42,
            },
            {
                _time: 2025-04-25T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2025-04-25T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2025-04-25T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2025-04-25T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2025-04-25T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2025-04-25T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2025-04-25T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2025-04-25T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2025-04-25T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.22,
            },
            {
                _time: 2025-04-25T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.02,
            },
            {
                _time: 2025-04-25T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.82,
            },
            {
                _time: 2025-04-25T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.02,
            },
            {
                _time: 2025-04-25T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.22,
            },
            {
                _time: 2025-04-26T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.52,
            },
            {
                _time: 2025-04-26T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.02,
            },
            {
                _time: 2025-04-26T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.62,
            },
            {
                _time: 2025-04-26T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.02,
            },
            {
                _time: 2025-04-26T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.62,
            },
            {
                _time: 2025-04-26T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.22,
            },
            {
                _time: 2025-04-26T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.32,
            },
            {
                _time: 2025-04-26T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2025-04-26T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2025-04-26T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2025-04-26T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2025-04-26T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.52,
            },
            {
                _time: 2025-04-26T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2025-04-26T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.32,
            },
            {
                _time: 2025-04-26T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.32,
            },
            {
                _time: 2025-04-26T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2025-04-26T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.02,
            },
            {
                _time: 2025-04-26T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2025-04-26T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2025-04-26T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2025-04-26T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.82,
            },
            {
                _time: 2025-04-26T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.82,
            },
            {
                _time: 2025-04-26T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.92,
            },
            {
                _time: 2025-04-27T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.42,
            },
            {
                _time: 2025-04-27T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.82,
            },
            {
                _time: 2025-04-27T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.32,
            },
            {
                _time: 2025-04-27T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.22,
            },
            {
                _time: 2025-04-27T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.92,
            },
            {
                _time: 2025-04-27T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.42,
            },
            {
                _time: 2025-04-27T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.72,
            },
            {
                _time: 2025-04-27T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2025-04-27T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2025-04-27T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2025-04-27T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.22,
            },
            {
                _time: 2025-04-27T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2025-04-27T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.52,
            },
            {
                _time: 2025-04-27T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2025-04-27T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.02,
            },
            {
                _time: 2025-04-27T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2025-04-27T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.42,
            },
            {
                _time: 2025-04-27T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2025-04-27T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.32,
            },
            {
                _time: 2025-04-27T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.42,
            },
            {
                _time: 2025-04-27T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.22,
            },
            {
                _time: 2025-04-27T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.12,
            },
            {
                _time: 2025-04-27T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.42,
            },
            {
                _time: 2025-04-28T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.92,
            },
            {
                _time: 2025-04-28T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.42,
            },
            {
                _time: 2025-04-28T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.02,
            },
            {
                _time: 2025-04-28T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.02,
            },
            {
                _time: 2025-04-28T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.62,
            },
            {
                _time: 2025-04-28T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.42,
            },
            {
                _time: 2025-04-28T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.72,
            },
            {
                _time: 2025-04-28T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.02,
            },
            {
                _time: 2025-04-28T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2025-04-28T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2025-04-28T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.62,
            },
            {
                _time: 2025-04-28T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2025-04-28T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2025-04-28T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.12,
            },
            {
                _time: 2025-04-28T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.32,
            },
            {
                _time: 2025-04-28T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.02,
            },
            {
                _time: 2025-04-28T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.02,
            },
            {
                _time: 2025-04-28T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2025-04-28T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.32,
            },
            {
                _time: 2025-04-28T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.62,
            },
            {
                _time: 2025-04-28T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.12,
            },
            {
                _time: 2025-04-28T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.22,
            },
            {
                _time: 2025-04-28T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.52,
            },
            {
                _time: 2025-04-29T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.42,
            },
            {
                _time: 2025-04-29T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.92,
            },
            {
                _time: 2025-04-29T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.52,
            },
            {
                _time: 2025-04-29T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 4.42,
            },
            {
                _time: 2025-04-29T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.52,
            },
            {
                _time: 2025-04-29T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.12,
            },
            {
                _time: 2025-04-29T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.42,
            },
            {
                _time: 2025-04-29T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.02,
            },
            {
                _time: 2025-04-29T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2025-04-29T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2025-04-29T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.12,
            },
            {
                _time: 2025-04-29T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2025-04-29T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2025-04-29T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2025-04-29T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2025-04-29T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2025-04-29T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.42,
            },
            {
                _time: 2025-04-29T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2025-04-29T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2025-04-29T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.42,
            },
            {
                _time: 2025-04-29T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.42,
            },
            {
                _time: 2025-04-29T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.32,
            },
            {
                _time: 2025-04-29T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.72,
            },
            {
                _time: 2025-04-30T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.62,
            },
            {
                _time: 2025-04-30T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.32,
            },
            {
                _time: 2025-04-30T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.82,
            },
            {
                _time: 2025-04-30T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 5.72,
            },
            {
                _time: 2025-04-30T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.62,
            },
            {
                _time: 2025-04-30T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.92,
            },
            {
                _time: 2025-04-30T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.02,
            },
            {
                _time: 2025-04-30T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2025-04-30T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2025-04-30T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.22,
            },
            {
                _time: 2025-04-30T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2025-04-30T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2025-04-30T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.12,
            },
            {
                _time: 2025-04-30T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.22,
            },
            {
                _time: 2025-04-30T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.22,
            },
            {
                _time: 2025-04-30T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.82,
            },
            {
                _time: 2025-04-30T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2025-04-30T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2025-04-30T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2025-04-30T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2025-04-30T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.22,
            },
            {
                _time: 2025-04-30T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.92,
            },
            {
                _time: 2025-04-30T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.22,
            },
            {
                _time: 2025-05-01T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.22,
            },
            {
                _time: 2025-05-01T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.82,
            },
            {
                _time: 2025-05-01T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.52,
            },
            {
                _time: 2025-05-01T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.32,
            },
            {
                _time: 2025-05-01T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 6.92,
            },
            {
                _time: 2025-05-01T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.12,
            },
            {
                _time: 2025-05-01T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.12,
            },
            {
                _time: 2025-05-01T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2025-05-01T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2025-05-01T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2025-05-01T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.82,
            },
            {
                _time: 2025-05-01T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.42,
            },
            {
                _time: 2025-05-01T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2025-05-01T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2025-05-01T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2025-05-01T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2025-05-01T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.02,
            },
            {
                _time: 2025-05-01T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2025-05-01T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2025-05-01T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2025-05-01T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.02,
            },
            {
                _time: 2025-05-01T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.22,
            },
        ],
    )

data
    |> to(bucket: "forecast")
