import "array"
data =
    array.from(
        rows: [
            {
                _time: 2024-05-30T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.32,
            },
            {
                _time: 2024-05-30T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.52,
            },
            {
                _time: 2024-05-30T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.52,
            },
            {
                _time: 2024-05-30T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2024-05-30T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2024-05-30T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.02,
            },
            {
                _time: 2024-05-30T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2024-05-30T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.02,
            },
            {
                _time: 2024-05-31T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2024-05-31T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.82,
            },
            {
                _time: 2024-05-31T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2024-05-31T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.02,
            },
            {
                _time: 2024-05-31T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2024-05-31T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2024-05-31T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-05-31T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2024-05-31T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2024-05-31T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2024-05-31T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2024-05-31T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2024-05-31T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-05-31T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2024-05-31T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2024-05-31T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2024-05-31T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2024-05-31T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-05-31T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2024-05-31T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-05-31T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-05-31T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-05-31T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-01T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-06-01T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-01T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2024-06-01T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2024-06-01T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2024-06-01T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2024-06-01T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-01T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-01T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-06-01T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2024-06-01T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2024-06-01T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2024-06-01T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-01T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-01T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2024-06-01T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2024-06-01T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2024-06-01T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2024-06-01T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.02,
            },
            {
                _time: 2024-06-01T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2024-06-01T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2024-06-01T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2024-06-01T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2024-06-02T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.22,
            },
            {
                _time: 2024-06-02T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.22,
            },
            {
                _time: 2024-06-02T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.22,
            },
            {
                _time: 2024-06-02T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2024-06-02T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.02,
            },
            {
                _time: 2024-06-02T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.72,
            },
            {
                _time: 2024-06-02T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.52,
            },
            {
                _time: 2024-06-02T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.02,
            },
            {
                _time: 2024-06-02T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2024-06-02T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2024-06-02T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.12,
            },
            {
                _time: 2024-06-02T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.72,
            },
            {
                _time: 2024-06-02T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.02,
            },
            {
                _time: 2024-06-02T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.92,
            },
            {
                _time: 2024-06-02T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.92,
            },
            {
                _time: 2024-06-02T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-02T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.52,
            },
            {
                _time: 2024-06-02T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2024-06-02T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.72,
            },
            {
                _time: 2024-06-02T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.02,
            },
            {
                _time: 2024-06-02T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-02T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2024-06-02T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2024-06-03T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2024-06-03T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.82,
            },
            {
                _time: 2024-06-03T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2024-06-03T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2024-06-03T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.92,
            },
            {
                _time: 2024-06-03T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2024-06-03T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2024-06-03T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.52,
            },
            {
                _time: 2024-06-03T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2024-06-03T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.02,
            },
            {
                _time: 2024-06-03T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2024-06-03T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2024-06-03T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2024-06-03T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2024-06-03T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2024-06-03T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.42,
            },
            {
                _time: 2024-06-03T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2024-06-03T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.62,
            },
            {
                _time: 2024-06-03T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2024-06-03T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.22,
            },
            {
                _time: 2024-06-03T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2024-06-03T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2024-06-03T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2024-06-04T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.62,
            },
            {
                _time: 2024-06-04T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.52,
            },
            {
                _time: 2024-06-04T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2024-06-04T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.92,
            },
            {
                _time: 2024-06-04T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2024-06-04T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2024-06-04T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2024-06-04T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2024-06-04T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2024-06-04T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2024-06-04T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.32,
            },
            {
                _time: 2024-06-04T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.82,
            },
            {
                _time: 2024-06-04T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-04T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.52,
            },
            {
                _time: 2024-06-04T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.62,
            },
            {
                _time: 2024-06-04T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.42,
            },
            {
                _time: 2024-06-04T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.52,
            },
            {
                _time: 2024-06-04T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2024-06-04T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.02,
            },
            {
                _time: 2024-06-04T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2024-06-04T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2024-06-04T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.02,
            },
            {
                _time: 2024-06-04T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.42,
            },
            {
                _time: 2024-06-05T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.72,
            },
            {
                _time: 2024-06-05T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.32,
            },
            {
                _time: 2024-06-05T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.22,
            },
            {
                _time: 2024-06-05T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.52,
            },
            {
                _time: 2024-06-05T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2024-06-05T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.22,
            },
            {
                _time: 2024-06-05T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.72,
            },
            {
                _time: 2024-06-05T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2024-06-05T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2024-06-05T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.22,
            },
            {
                _time: 2024-06-05T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.82,
            },
            {
                _time: 2024-06-05T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-05T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.62,
            },
            {
                _time: 2024-06-05T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.72,
            },
            {
                _time: 2024-06-05T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.72,
            },
            {
                _time: 2024-06-05T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.42,
            },
            {
                _time: 2024-06-05T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.72,
            },
            {
                _time: 2024-06-05T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2024-06-05T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.22,
            },
            {
                _time: 2024-06-05T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2024-06-05T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-05T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2024-06-05T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2024-06-06T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2024-06-06T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.52,
            },
            {
                _time: 2024-06-06T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.32,
            },
            {
                _time: 2024-06-06T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.72,
            },
            {
                _time: 2024-06-06T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.82,
            },
            {
                _time: 2024-06-06T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2024-06-06T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.52,
            },
            {
                _time: 2024-06-06T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2024-06-06T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.42,
            },
            {
                _time: 2024-06-06T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-06T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.92,
            },
            {
                _time: 2024-06-06T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2024-06-06T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2024-06-06T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.02,
            },
            {
                _time: 2024-06-06T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.92,
            },
            {
                _time: 2024-06-06T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2024-06-06T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.02,
            },
            {
                _time: 2024-06-06T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.52,
            },
            {
                _time: 2024-06-06T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.02,
            },
            {
                _time: 2024-06-06T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2024-06-06T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2024-06-06T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.32,
            },
            {
                _time: 2024-06-06T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2024-06-07T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.92,
            },
            {
                _time: 2024-06-07T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.52,
            },
            {
                _time: 2024-06-07T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.52,
            },
            {
                _time: 2024-06-07T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.92,
            },
            {
                _time: 2024-06-07T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2024-06-07T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-07T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.12,
            },
            {
                _time: 2024-06-07T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.52,
            },
            {
                _time: 2024-06-07T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.72,
            },
            {
                _time: 2024-06-07T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.52,
            },
            {
                _time: 2024-06-07T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.02,
            },
            {
                _time: 2024-06-07T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.62,
            },
            {
                _time: 2024-06-07T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.92,
            },
            {
                _time: 2024-06-07T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.02,
            },
            {
                _time: 2024-06-07T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.82,
            },
            {
                _time: 2024-06-07T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.42,
            },
            {
                _time: 2024-06-07T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.52,
            },
            {
                _time: 2024-06-07T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-07T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2024-06-07T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2024-06-07T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.92,
            },
            {
                _time: 2024-06-07T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2024-06-07T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2024-06-08T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.72,
            },
            {
                _time: 2024-06-08T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2024-06-08T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2024-06-08T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.52,
            },
            {
                _time: 2024-06-08T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.62,
            },
            {
                _time: 2024-06-08T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.02,
            },
            {
                _time: 2024-06-08T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.62,
            },
            {
                _time: 2024-06-08T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2024-06-08T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.72,
            },
            {
                _time: 2024-06-08T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.52,
            },
            {
                _time: 2024-06-08T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2024-06-08T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2024-06-08T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.02,
            },
            {
                _time: 2024-06-08T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.32,
            },
            {
                _time: 2024-06-08T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.32,
            },
            {
                _time: 2024-06-08T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.02,
            },
            {
                _time: 2024-06-08T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2024-06-08T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2024-06-08T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2024-06-08T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.72,
            },
            {
                _time: 2024-06-08T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2024-06-08T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2024-06-08T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.12,
            },
            {
                _time: 2024-06-09T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.32,
            },
            {
                _time: 2024-06-09T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.02,
            },
            {
                _time: 2024-06-09T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.92,
            },
            {
                _time: 2024-06-09T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.32,
            },
            {
                _time: 2024-06-09T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.32,
            },
            {
                _time: 2024-06-09T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-09T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.52,
            },
            {
                _time: 2024-06-09T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.12,
            },
            {
                _time: 2024-06-09T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.22,
            },
            {
                _time: 2024-06-09T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.12,
            },
            {
                _time: 2024-06-09T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.92,
            },
            {
                _time: 2024-06-09T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.42,
            },
            {
                _time: 2024-06-09T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.82,
            },
            {
                _time: 2024-06-09T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.02,
            },
            {
                _time: 2024-06-09T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.92,
            },
            {
                _time: 2024-06-09T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.52,
            },
            {
                _time: 2024-06-09T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.32,
            },
            {
                _time: 2024-06-09T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.92,
            },
            {
                _time: 2024-06-09T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.12,
            },
            {
                _time: 2024-06-09T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.42,
            },
            {
                _time: 2024-06-09T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.22,
            },
            {
                _time: 2024-06-09T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
        ],
    )

data
    |> to(bucket: "forecast")
