import "array"
data =
    array.from(
        rows: [
            {
                _time: 2023-07-06T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.62,
            },
            {
                _time: 2023-07-06T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2023-07-06T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2023-07-06T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2023-07-06T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-06T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2023-07-06T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.52,
            },
            {
                _time: 2023-07-06T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.32,
            },
            {
                _time: 2023-07-06T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.12,
            },
            {
                _time: 2023-07-06T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.52,
            },
            {
                _time: 2023-07-06T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-06T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.12,
            },
            {
                _time: 2023-07-06T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-06T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.82,
            },
            {
                _time: 2023-07-06T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.62,
            },
            {
                _time: 2023-07-06T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-06T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2023-07-06T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.32,
            },
            {
                _time: 2023-07-06T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.82,
            },
            {
                _time: 2023-07-06T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 9.92,
            },
            {
                _time: 2023-07-07T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.72,
            },
            {
                _time: 2023-07-07T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.12,
            },
            {
                _time: 2023-07-07T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 7.82,
            },
            {
                _time: 2023-07-07T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 8.62,
            },
            {
                _time: 2023-07-07T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.42,
            },
            {
                _time: 2023-07-07T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.42,
            },
            {
                _time: 2023-07-07T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.82,
            },
            {
                _time: 2023-07-07T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.32,
            },
            {
                _time: 2023-07-07T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.92,
            },
            {
                _time: 2023-07-07T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.82,
            },
            {
                _time: 2023-07-07T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.92,
            },
            {
                _time: 2023-07-07T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.02,
            },
            {
                _time: 2023-07-07T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.72,
            },
            {
                _time: 2023-07-07T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.32,
            },
            {
                _time: 2023-07-07T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.32,
            },
            {
                _time: 2023-07-07T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.82,
            },
            {
                _time: 2023-07-07T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 26.32,
            },
            {
                _time: 2023-07-07T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.52,
            },
            {
                _time: 2023-07-07T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.42,
            },
            {
                _time: 2023-07-07T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2023-07-07T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2023-07-07T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.72,
            },
            {
                _time: 2023-07-07T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.52,
            },
            {
                _time: 2023-07-08T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 11.12,
            },
            {
                _time: 2023-07-08T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.42,
            },
            {
                _time: 2023-07-08T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.12,
            },
            {
                _time: 2023-07-08T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 10.42,
            },
            {
                _time: 2023-07-08T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.22,
            },
            {
                _time: 2023-07-08T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2023-07-08T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2023-07-08T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-08T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.32,
            },
            {
                _time: 2023-07-08T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.22,
            },
            {
                _time: 2023-07-08T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.42,
            },
            {
                _time: 2023-07-08T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 29.62,
            },
            {
                _time: 2023-07-08T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 30.22,
            },
            {
                _time: 2023-07-08T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 30.92,
            },
            {
                _time: 2023-07-08T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 30.92,
            },
            {
                _time: 2023-07-08T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 30.22,
            },
            {
                _time: 2023-07-08T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.32,
            },
            {
                _time: 2023-07-08T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.42,
            },
            {
                _time: 2023-07-08T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.92,
            },
            {
                _time: 2023-07-08T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2023-07-08T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-08T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.72,
            },
            {
                _time: 2023-07-08T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.02,
            },
            {
                _time: 2023-07-09T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2023-07-09T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2023-07-09T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.72,
            },
            {
                _time: 2023-07-09T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2023-07-09T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.22,
            },
            {
                _time: 2023-07-09T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.62,
            },
            {
                _time: 2023-07-09T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.82,
            },
            {
                _time: 2023-07-09T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.92,
            },
            {
                _time: 2023-07-09T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.62,
            },
            {
                _time: 2023-07-09T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 29.12,
            },
            {
                _time: 2023-07-09T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 30.42,
            },
            {
                _time: 2023-07-09T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 31.32,
            },
            {
                _time: 2023-07-09T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 31.92,
            },
            {
                _time: 2023-07-09T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 32.32,
            },
            {
                _time: 2023-07-09T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 32.32,
            },
            {
                _time: 2023-07-09T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 31.42,
            },
            {
                _time: 2023-07-09T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 29.62,
            },
            {
                _time: 2023-07-09T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.22,
            },
            {
                _time: 2023-07-09T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.42,
            },
            {
                _time: 2023-07-09T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.12,
            },
            {
                _time: 2023-07-09T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.82,
            },
            {
                _time: 2023-07-09T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.62,
            },
            {
                _time: 2023-07-09T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.92,
            },
            {
                _time: 2023-07-10T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-10T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.72,
            },
            {
                _time: 2023-07-10T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2023-07-10T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.82,
            },
            {
                _time: 2023-07-10T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.42,
            },
            {
                _time: 2023-07-10T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.92,
            },
            {
                _time: 2023-07-10T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-10T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.42,
            },
            {
                _time: 2023-07-10T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.62,
            },
            {
                _time: 2023-07-10T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 26.82,
            },
            {
                _time: 2023-07-10T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.32,
            },
            {
                _time: 2023-07-10T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.22,
            },
            {
                _time: 2023-07-10T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.62,
            },
            {
                _time: 2023-07-10T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.92,
            },
            {
                _time: 2023-07-10T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 29.02,
            },
            {
                _time: 2023-07-10T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.52,
            },
            {
                _time: 2023-07-10T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.42,
            },
            {
                _time: 2023-07-10T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.52,
            },
            {
                _time: 2023-07-10T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.02,
            },
            {
                _time: 2023-07-10T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.12,
            },
            {
                _time: 2023-07-10T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.52,
            },
            {
                _time: 2023-07-10T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.62,
            },
            {
                _time: 2023-07-10T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-11T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-11T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.62,
            },
            {
                _time: 2023-07-11T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2023-07-11T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.32,
            },
            {
                _time: 2023-07-11T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.42,
            },
            {
                _time: 2023-07-11T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.42,
            },
            {
                _time: 2023-07-11T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.42,
            },
            {
                _time: 2023-07-11T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.22,
            },
            {
                _time: 2023-07-11T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.02,
            },
            {
                _time: 2023-07-11T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 26.12,
            },
            {
                _time: 2023-07-11T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 26.92,
            },
            {
                _time: 2023-07-11T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.42,
            },
            {
                _time: 2023-07-11T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 28.02,
            },
            {
                _time: 2023-07-11T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.72,
            },
            {
                _time: 2023-07-11T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 27.32,
            },
            {
                _time: 2023-07-11T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 26.72,
            },
            {
                _time: 2023-07-11T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 25.62,
            },
            {
                _time: 2023-07-11T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.12,
            },
            {
                _time: 2023-07-11T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.32,
            },
            {
                _time: 2023-07-11T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.62,
            },
            {
                _time: 2023-07-11T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.32,
            },
            {
                _time: 2023-07-11T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.42,
            },
            {
                _time: 2023-07-11T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.72,
            },
            {
                _time: 2023-07-12T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-12T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-12T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2023-07-12T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.12,
            },
            {
                _time: 2023-07-12T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-12T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.02,
            },
            {
                _time: 2023-07-12T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.02,
            },
            {
                _time: 2023-07-12T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.32,
            },
            {
                _time: 2023-07-12T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.02,
            },
            {
                _time: 2023-07-12T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.92,
            },
            {
                _time: 2023-07-12T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.52,
            },
            {
                _time: 2023-07-12T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.72,
            },
            {
                _time: 2023-07-12T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.22,
            },
            {
                _time: 2023-07-12T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.32,
            },
            {
                _time: 2023-07-12T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.32,
            },
            {
                _time: 2023-07-12T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.02,
            },
            {
                _time: 2023-07-12T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.12,
            },
            {
                _time: 2023-07-12T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.82,
            },
            {
                _time: 2023-07-12T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2023-07-12T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-12T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2023-07-12T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.32,
            },
            {
                _time: 2023-07-12T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.72,
            },
            {
                _time: 2023-07-13T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.62,
            },
            {
                _time: 2023-07-13T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2023-07-13T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.82,
            },
            {
                _time: 2023-07-13T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.02,
            },
            {
                _time: 2023-07-13T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.12,
            },
            {
                _time: 2023-07-13T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2023-07-13T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.02,
            },
            {
                _time: 2023-07-13T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2023-07-13T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.12,
            },
            {
                _time: 2023-07-13T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.32,
            },
            {
                _time: 2023-07-13T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.02,
            },
            {
                _time: 2023-07-13T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.42,
            },
            {
                _time: 2023-07-13T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.92,
            },
            {
                _time: 2023-07-13T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.22,
            },
            {
                _time: 2023-07-13T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.02,
            },
            {
                _time: 2023-07-13T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.82,
            },
            {
                _time: 2023-07-13T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-13T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.42,
            },
            {
                _time: 2023-07-13T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.52,
            },
            {
                _time: 2023-07-13T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.72,
            },
            {
                _time: 2023-07-13T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.32,
            },
            {
                _time: 2023-07-13T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.42,
            },
            {
                _time: 2023-07-13T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.82,
            },
            {
                _time: 2023-07-14T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2023-07-14T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2023-07-14T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.72,
            },
            {
                _time: 2023-07-14T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 12.92,
            },
            {
                _time: 2023-07-14T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.82,
            },
            {
                _time: 2023-07-14T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2023-07-14T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-14T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.72,
            },
            {
                _time: 2023-07-14T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.12,
            },
            {
                _time: 2023-07-14T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.42,
            },
            {
                _time: 2023-07-14T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.22,
            },
            {
                _time: 2023-07-14T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.92,
            },
            {
                _time: 2023-07-14T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.92,
            },
            {
                _time: 2023-07-14T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.22,
            },
            {
                _time: 2023-07-14T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.22,
            },
            {
                _time: 2023-07-14T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 24.22,
            },
            {
                _time: 2023-07-14T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-14T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.32,
            },
            {
                _time: 2023-07-14T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.42,
            },
            {
                _time: 2023-07-14T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.92,
            },
            {
                _time: 2023-07-14T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.72,
            },
            {
                _time: 2023-07-14T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2023-07-14T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.22,
            },
            {
                _time: 2023-07-15T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.02,
            },
            {
                _time: 2023-07-15T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2023-07-15T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2023-07-15T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2023-07-15T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.42,
            },
            {
                _time: 2023-07-15T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.92,
            },
            {
                _time: 2023-07-15T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 17.62,
            },
            {
                _time: 2023-07-15T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 19.22,
            },
            {
                _time: 2023-07-15T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.42,
            },
            {
                _time: 2023-07-15T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.52,
            },
            {
                _time: 2023-07-15T10:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.22,
            },
            {
                _time: 2023-07-15T11:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-15T12:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.02,
            },
            {
                _time: 2023-07-15T13:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.22,
            },
            {
                _time: 2023-07-15T14:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 23.12,
            },
            {
                _time: 2023-07-15T15:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.82,
            },
            {
                _time: 2023-07-15T16:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.62,
            },
            {
                _time: 2023-07-15T17:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.32,
            },
            {
                _time: 2023-07-15T18:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.52,
            },
            {
                _time: 2023-07-15T19:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.92,
            },
            {
                _time: 2023-07-15T20:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 15.82,
            },
            {
                _time: 2023-07-15T21:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2023-07-15T22:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.32,
            },
            {
                _time: 2023-07-16T00:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.52,
            },
            {
                _time: 2023-07-16T01:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2023-07-16T02:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.12,
            },
            {
                _time: 2023-07-16T03:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 13.32,
            },
            {
                _time: 2023-07-16T04:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 14.92,
            },
            {
                _time: 2023-07-16T05:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 16.42,
            },
            {
                _time: 2023-07-16T06:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 18.42,
            },
            {
                _time: 2023-07-16T07:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 20.12,
            },
            {
                _time: 2023-07-16T08:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 21.42,
            },
            {
                _time: 2023-07-16T09:00:00Z,
                _measurement: "temp_air",
                _field: "value",
                _value: 22.52,
            },
        ],
    )

data
    |> to(bucket: "forecast")
