import "array"
data =
    array.from(
        rows: [
            {
                _time: 2023-02-14T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-14T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-14T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-14T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-14T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-14T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-14T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-14T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-15T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-15T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-15T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-15T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.03,
            },
            {
                _time: 2023-02-15T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-15T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-15T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-15T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 1.54,
            },
            {
                _time: 2023-02-16T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-16T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-16T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-16T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-16T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-16T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-16T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-16T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-16T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-17T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-17T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-17T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-17T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-17T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-17T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-17T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-17T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.14,
            },
            {
                _time: 2023-02-17T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-17T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-17T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-17T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-17T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-17T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-17T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-17T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-17T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-18T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-18T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-18T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-18T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-18T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-18T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 7.2,
            },
            {
                _time: 2023-02-18T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.69,
            },
            {
                _time: 2023-02-18T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-18T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 6.17,
            },
            {
                _time: 2023-02-18T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-18T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-18T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-18T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.66,
            },
            {
                _time: 2023-02-18T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.14,
            },
            {
                _time: 2023-02-18T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 5.14,
            },
            {
                _time: 2023-02-19T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-19T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-19T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-19T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-19T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-19T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-19T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-19T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-19T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-19T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-19T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-19T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-19T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-19T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-19T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-20T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-20T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-20T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-20T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-20T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-20T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-20T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-20T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-20T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-20T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-20T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-20T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-20T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-20T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-21T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-21T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.06,
            },
            {
                _time: 2023-02-21T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-21T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-21T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-21T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-21T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-21T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-21T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-21T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-21T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-21T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-21T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-21T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-22T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-22T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-22T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-22T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-22T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-22T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-22T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-22T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-22T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-22T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-23T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-23T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 2.57,
            },
            {
                _time: 2023-02-23T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-23T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-23T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-23T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-23T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-23T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-23T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-23T22:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T00:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T01:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T02:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T03:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T04:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T05:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T06:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T07:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.09,
            },
            {
                _time: 2023-02-24T08:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-24T09:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-24T10:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-24T11:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-24T12:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-24T13:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-24T14:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.63,
            },
            {
                _time: 2023-02-24T15:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-24T16:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 4.12,
            },
            {
                _time: 2023-02-24T17:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-24T18:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-24T19:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-24T20:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
            {
                _time: 2023-02-24T21:00:00Z,
                _measurement: "wind_speed",
                _field: "value",
                _value: 3.6,
            },
        ],
    )

data
    |> to(bucket: "forecast")
